clear all;
clc;
rp = input('pass ripple freq (0.5000): ');
rs = input('stop ripple freq(40): ');
fp = input('pass band freq(2000): ');
fs = input('stop band freq(3000): ');
f = input('sample freq(10000): ');
w1= 2*fp/f;
w2=2*fs/f;
[n]= buttord(w1 ,w2,rp,rs);
wn=[w1,w2];
[b,a]= butter(n,wn,'stop'); 
w=0:0.1:pi;
[h,p]= freqz(b,a,w);
g= 20* log10(abs(h));
A=angle(h);
subplot (2,1,1); plot(p/pi,g);
ylabel('amp');
xlabel('ferq');
title('amp,freq');
subplot (2,1,2); plot(p/pi,A);
xlabel('normal. freq');
ylabel('phase');
title('normal. freq,phase');
